[project]
name = "poketerm"
version = "0.1.0"
description = "A CLI tool to get random pokemon ASCII art and pokedex info"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "pillow>=12.1.1",
    "platformdirs>=4.12.2",
    "rich>=14.3.3",
]

[project.scripts]
poketerm = "poketerm.cli:main"

[build-system]
requires = ["uv_build>=0.8.17,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.10",
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]
